### ISSUE TITLE
FontSizeView

### ISSUE THREAD

**Issue by suri0000** [suri0000/wwdc2024#13]
## 🛠 Issue
- FontSizeView 만들기

## 📝 To-do
- [x] FontSizeView UI
- [x] 누르면 사이즈 커지게 하기
- [x] 넥스트 버튼 연결
- [x] 다음 파일 추가
