### ISSUE TITLE
ScreenLockView 작업

### ISSUE THREAD

**Issue by suri0000** [suri0000/wwdc2024#15]
## 🛠 Issue
- ScreenLockView를 만듭니다.

## 📝 To-do
- [x] ScreenLockView UI
- [x] 화면 회전 측정
- [x] 배 움직이기
- [x] 다음 화면 파일 추가
- [x] 배, 파도 파일 추가
